CREATE DATABASE Category;

CREATE TABLE CATEGORY(
ID INT PRIMARY KEY IDENTITY(1,1),
NAME VARCHAR(20));

CREATE TABLE SUBCATEGORY(
ID INT PRIMARY KEY IDENTITY(101,1),
CATEGORY_ID INT FOREIGN KEY REFERENCES CATEGORY(ID),
NAME VARCHAR(20));

CREATE TABLE ITEM(
ID INT PRIMARY KEY IDENTITY(201,1),
SUBCATEGORY_ID INT FOREIGN KEY REFERENCES SUBCATEGORY(ID),
NAME VARCHAR(20),
[DESCRIPTION] VARCHAR(50));

SELECT * FROM INFORMATION_SCHEMA.TABLES
SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'ITEM'

--INSERTION EXAMPLE 1
INSERT INTO CATEGORY(NAME) VALUES ('EMPLOYEE');

INSERT INTO SUBCATEGORY(CATEGORY_ID,NAME) VALUES (1,'FULL TIME')
INSERT INTO SUBCATEGORY(CATEGORY_ID,NAME) VALUES (1,'PART TIME')

INSERT INTO ITEM(SUBCATEGORY_ID,NAME,[DESCRIPTION]) VALUES (101, 'RUTHVIK', 'BACK-END DEVELOPER')
INSERT INTO ITEM(SUBCATEGORY_ID,NAME,[DESCRIPTION]) VALUES (101, 'ROSHAN', 'FRONT-END DEVELOPER')
INSERT INTO ITEM(SUBCATEGORY_ID,NAME,[DESCRIPTION]) VALUES (102, 'KAMALA', 'DATA ANALYST')
INSERT INTO ITEM(SUBCATEGORY_ID,NAME,[DESCRIPTION]) VALUES (102, 'RACHANA', 'HR')

--INSERTION EXAMPLE 2
INSERT INTO CATEGORY(NAME) VALUES ('VEHICLE');

INSERT INTO SUBCATEGORY(CATEGORY_ID,NAME) VALUES (2,'TWO WHEELS')
INSERT INTO SUBCATEGORY(CATEGORY_ID,NAME) VALUES (2,'FOUR WHEELS')

INSERT INTO ITEM(SUBCATEGORY_ID,NAME,[DESCRIPTION]) VALUES (103, 'YAMAHA', 'FZ-250 2 STROKE')
INSERT INTO ITEM(SUBCATEGORY_ID,NAME,[DESCRIPTION]) VALUES (103, 'HONDA', 'CBR 650 4 STROKE')
INSERT INTO ITEM(SUBCATEGORY_ID,NAME,[DESCRIPTION]) VALUES (104, 'TATA', 'HARRIER OFF ROADER')
INSERT INTO ITEM(SUBCATEGORY_ID,NAME,[DESCRIPTION]) VALUES (104, 'FORD', 'ECOSPORT HIGHWAY RUN')

SELECT * FROM CATEGORY
SELECT * FROM SUBCATEGORY
SELECT * FROM ITEM




